Fixed up version number, putting it back in line with PyPI
